### PR TITLE
Allow IDP cert as array

### PR DESCRIPTION
**Pull request by fpersico**

### CODE REVIEW

**Comment by gunzip** [comment]
@cloudify  @fpersico note that the io-backend uses this version of the spid-passport package:

https://github.com/teamdigitale/io-backend/blob/master/package.json#L62

which has other fixes that diverge from the master branch

**Comment by cloudify** [comment]
thanks for the headsup @gunzip -  @fpersico we can create a branch from that commit and apply your change there

**Comment by fpersico** [comment]
@gunzip I know this PR changes the repository https://github.com/teamdigitale/io-backend/pull/400

**Comment by gunzip** [comment]
> @gunzip I know this PR changes the repository [teamdigitale/io-backend#400](https://github.com/teamdigitale/io-backend/pull/400)

right but i guess you have to backport the changes

**Review by cloudify — APPROVED** [review]

**Pull request merged**
